playerTabFormat: "{player_nickname}"
joinMessage: "&7{player_nickname} &r&6зашел на сервер."
leaveMessage: "&7{player_nickname} &6вышел с сервера."
joinSoundEnabled: false
joinSound: "ENTITY_EXPERIENCE_ORB_PICKUP"
leaveSoundEnabled: false
leaveSound: "ENTITY_EXPERIENCE_ORB_PICKUP"
joinNotificationsDefault: true
joinNotificationsEnabled: true
leaveNotificationsDefault: true
leaveNotificationsEnabled: true
# level progress
levelProgressUncompletedColor: "&8"
levelProgressCompletedColor: "&2"
levelProgressHalfColor: "&a"
# kick and ban parameters
kickFormat: "&7{player_nickname} &cбыл кикнут по причине: {player_message}"
banFormat: "&7{player_nickname} &c&lбыл забанен по причине: {player_message}"
# chat parameters
chat: "&7{player_nickname}&f: {player_message}"
globalChat: "&6[G] &7{player_nickname}&f: {player_message}"
localChat: "&9[L] &7{player_nickname}&f: {player_message}"
ifNoOneHeardTheMessage: "&cВаше сообщение никто не услышал"
globalPrefix: "!"
localRadius: 100
isGlobalEnabled: true
isChatClickable: true
clickableType: 1
clickableValue: "/msg {player_nickname}"
isChatHover: true
hoverMessage: "{player_nickname}\n&7Уровень: &6{player_level}"